### ISSUE TITLE
Fetching RestAPI to chart

### ISSUE THREAD

**Issue by LuqmaanSiddeeq** [rwbrockhoff/chartjsdemo#2]
i just wanted to know how to fetch an API data to the chart. for example i have date and count of population in a country. so i want to show this in a chart using chart JS. using raw data or manual data is okay to go. but when handling realtime, what and how do i do that in ReactJS.

**Comment by rwbrockhoff** [comment]
Hey! Great question. That's definitely more in the scope of how to handle data in React--compared to how Chart.js handles data. You'll want to make you fetch requests in your ComponentDidMount or in your useEffect hook. Once you have your data loaded, you can hopefully follow my demo pretty easily by passing it to your chart component instead of my manual dataset.

I would jump into the React docs and make sure you understand the lifecycle methods and how React works in regards to async tasks and fetching data from APIs. If you're wanting to see the React Hooks approach to data fetching, I'd check out [this great article](https://www.robinwieruch.de/react-hooks-fetch-data). 

Best of luck!

**Comment by LuqmaanSiddeeq** [comment]
https://api.covid19api.com/dayone/country/sri-lanka/status/confirmed

**Comment by LuqmaanSiddeeq** [comment]
Thanks for your answer. I looked into that. I can retrieve the data fro API but still, I confused on how to pass the fetched data to Charts.

https://api.covid19api.com/dayone/country/sri-lanka/status/confirmed

This is the API that I use to retrieve to my application. 
I was like "no idea" on how to get it done. Can you take me around this problem on how to solve this? 
Since I'm new to React.

**Comment by LuqmaanSiddeeq** [comment]
> 
> 
> Hey! Great question. That's definitely more in the scope of how to handle data in React--compared to how Chart.js handles data. You'll want to make you fetch requests in your ComponentDidMount or in your useEffect hook. Once you have your data loaded, you can hopefully follow my demo pretty easily by passing it to your chart component instead of my manual dataset.
> 
> I would jump into the React docs and make sure you understand the lifecycle methods and how React works in regards to async tasks and fetching data from APIs. If you're wanting to see the React Hooks approach to data fetching, I'd check out [this great article](https://www.robinwieruch.de/react-hooks-fetch-data).
> 
> Best of luck!

Hey Ryan, Yeah just as a small thing. I Just assigned the API locations as variables and pushed. Now it works! Thanks for spending precious time to make me more understandable. Thank you so much! 

![image](https://user-images.githubusercontent.com/43641228/78962119-40338480-7b11-11ea-9512-bfd4f69bc449.png)

**Comment by rwbrockhoff** [comment]
You're absolutely welcome. Awesome chart! Glad to be of help :)
